# Configurações de build para o Netlify

[build]
  # Comando para fazer o build do projeto Next.js
  command = "npm run build"
  
  # Diretório que contém os ficheiros do build (gerado pelo Next.js)
  publish = ".next"

# Redirecionamentos e reescritas para garantir que o roteamento do Next.js funcione
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200